// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLicO2YPGkk4KbVgJ7S1nar61Zf4VCqQ',
    appId: '1:1012229817540:web:9bddcf08b8771fe3997591',
    messagingSenderId: '1012229817540',
    projectId: 'smoke-store-75d36',
    authDomain: 'smoke-store-75d36.firebaseapp.com',
    storageBucket: 'smoke-store-75d36.firebasestorage.app',
    measurementId: 'G-ZLEG0PE66T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_zc0DH2UEyRIhazpaQEYN8-ZHoBxsrrc',
    appId: '1:1012229817540:android:a15452653385a048997591',
    messagingSenderId: '1012229817540',
    projectId: 'smoke-store-75d36',
    storageBucket: 'smoke-store-75d36.firebasestorage.app',
  );
}
